import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "next-themes";
import { WalletAuthProvider } from "@/providers/WalletAuthProvider";
import "./globals.css";
import { KeyPairAuthProvider } from "@/providers/KeyPairAuthProvider";
import { QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <KeyPairAuthProvider>
            <WalletAuthProvider>
              <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
                {children}
                <Toaster />
              </ThemeProvider>
            </WalletAuthProvider>
          </KeyPairAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
